apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi-deployment
  labels:
    app: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi-conatiner
        image: sunbirdreg.azurecr.io/todoapi
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registrysecret
