apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi-deployment
  labels:
    app: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi-conatiner
        image: sunbirdreg.azurecr.io/todoapi:78bc3bbcb61c10c69f3a7587563fb3aeb9d5a4a3
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi-front
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30008
  selector:
    app: todoapi
    # this is private lb service