@TodoApi_HostAddress = https://learningapp.azure-api.net/echo

GET {{TodoApi_HostAddress}}/resource/?param1=test&param2=12
Accept: application/json
ocp-apim-subscription-key: ed4946d480484015899ff3a95e63e2ad


###
