@TodoApi_HostAddress = https://jiodemoapi.azure-api.net/echo

GET {{TodoApi_HostAddress}}/resource/?param1=test&param2=12
Accept: application/json
ocp-apim-subscription-key: 5cce3358f27c4a7bb99f7d50c8984591


###
